{
 "title": "VictoriaMetrics - Target statistics",
 "tags": [ "victoriametrics" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   { "name": "topk", "label": "Topk", "query": "5,10,15,20" },
   { "name": "resolution", "label": "Resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "label": "Jobs",
    "query": {
     "query": "label_values(vm_promscrape_scrape_pool_targets,scrape_job)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs - Percent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_scrape_pool_targets{status=\"up\", scrape_job!=\"\"}) / sum(vm_promscrape_scrape_pool_targets)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs - Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum(vm_promscrape_scrape_pool_targets{status=\"up\"}) by (scrape_job))",
     "legendFormat": "up"
    },
    {
     "expr": "sum(sum(vm_promscrape_scrape_pool_targets{status=\"down\"}) by (scrape_job))",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Targets - Percent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{status=\"up\"}) / sum(vm_promscrape_targets)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target - Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{status=\"up\"})",
     "legendFormat": "up"
    },
    {
     "expr": "sum(vm_promscrape_targets{status=\"down\"})",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "stat",
   "description": "for 24h",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Series",
   "type": "stat",
   "description": "Shows the number of [active time series](https://docs.victoriametrics.com/victoriametrics/faq/#what-is-an-active-time-series) with new data points inserted during the last hour. High value may result in ingestion slowdown.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{type=\"storage/hour_metric_ids\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top by Series [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk($topk, sum(scrape_series_current) by (instance))"
    }
   ]
  },
  {
   "title": "Top by Samples",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "topk($topk, sum(scrape_samples_scraped) by (instance))"
    }
   ]
  },
  {
   "title": "Top by Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "topk($topk, sum(scrape_response_size_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Top by Duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "topk($topk, sum(scrape_duration_seconds) by (instance))"
    }
   ]
  },
  { "title": "Stats by Targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Jobs Coverage",
   "type": "table",
   "description": "Процент работающих target в job",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(vm_promscrape_scrape_pool_targets, \"job\", \"$1\", \"scrape_job\", \"(.*)\")"
    },
    {
     "expr": "label_replace(sum(vm_promscrape_scrape_pool_targets{status=\"up\"}) by (scrape_job) / sum(vm_promscrape_scrape_pool_targets) by (scrape_job), \"job\", \"$1\", \"scrape_job\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "table",
   "description": "`Series` - Количество полученных серий\n\n`Series` - Количество полученных серий за 24ч\n\n`Series Limit` - Процент используемого [лимита](https://docs.victoriametrics.com/victoriametrics/vmagent/#cardinality-limiter) за 24ч \n\n`Samples` - полученые семплы/метрики\n\n`Dropped` - кол-во откинутых семплов (series_limit)\n\n`Relabeling` - кол-во замененных лейблов/меток\n\n`Size` - размер полученных семплов/метрик\n\n`Duration` - время получения семплов/метрик\n\n`Duration Limit` - Процент используемого лимита (scrape_timeout)",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{job=~\"$job\"}) by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_response_size_bytes{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds{job=~\"$job\"}) by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_samples_scraped{job=~\"$job\"} - scrape_samples_post_metric_relabeling{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_duration_seconds{job=~\"$job\"} / scrape_timeout_seconds{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_series_added{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_series_limit_samples_dropped{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_series_current{job=~\"$job\"} / scrape_series_limit{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(scrape_series_current{job=~\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top by Targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Series Add",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, sum(scrape_series_added{job=~\"$job\"}) by (job,instance))",
       "legendFormat": "{{ job }} - ({{ instance }})"
      }
     ]
    },
    {
     "title": "Samples",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, avg (scrape_samples_scraped{job=~\"$job\"}) by(job,instance)) ",
       "legendFormat": "{{ job }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Series [24h]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, sum(scrape_series_current{job=~\"$job\"}) by (job,instance))",
       "legendFormat": "{{ job }} - ({{ instance }})"
      }
     ]
    },
    {
     "title": "Relabeling",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, sum(scrape_samples_scraped{job=~\"$job\"} - scrape_samples_post_metric_relabeling{job=~\"$job\"}) by (job, instance))",
       "legendFormat": "{{ job }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($topk, avg (scrape_response_size_bytes{job=~\"$job\"}) by(job, instance))",
       "legendFormat": "{{ job }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Dropped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, sum(increase(scrape_series_limit_samples_dropped{job=~\"$job\"}[24h])) by (job, instance))",
       "legendFormat": "{{ job }} ({{ instance }})"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($topk, sum(scrape_duration_seconds{job=~\"$job\"}) by(job, instance))",
       "legendFormat": "{{ job }} ({{ instance }})"
      }
     ]
    }
   ]
  }
 ]
}