{
 "title": "VictoriaLogs Explorer - Docker",
 "tags": [
  "victorialogs",
  "docker"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "DS",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "source_type", "label": "source_type", "query": "docker_logs" },
   {
    "name": "host",
    "label": "Instance",
    "query": {
     "query": "_stream:{source_type=\"$source_type\"}"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "_stream:{host=\"$host\", source_type=\"$source_type\"}"
    }
   },
   {
    "name": "level",
    "label": "Level",
    "query": {
     "query": "_stream:{host=\"$host\", source_type=\"$source_type\", container_name=~\"$container.*\"}"
    }
   },
   { "name": "limit", "label": "Limit", "query": "1000,2500,5000,7500,10000" },
   { "name": "filter", "label": "Filter", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "Logs - Stats All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs - Top 5 By Container",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\"}\r\n| stats by (container_name) count() containers\r\n| sort by (containers desc)\r\n| limit 5",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Total - Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\"}\r\n| stats by (container_name) count()\r\n| count()",
       "legendFormat": "containers"
      }
     ]
    },
    {
     "title": "Total - Logs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\"}\r\n| stats count() ",
       "legendFormat": "logs"
      }
     ]
    },
    {
     "title": "Logs - Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\"}\r\n| stats by (container_name) rate() logs_rate\r\n| filter logs_rate: > 0",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Total - Logs level",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\"}\r\n| stats by (log.level) count() total\r\n| sort by (total desc)\r\n| limit 10",
       "legendFormat": "{{ log.level }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Stats Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top field-value pairs (facets)",
     "type": "table",
     "description": "Shows the most common field-value pairs \n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#facets-pipe",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 160 },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\", container_name=~\"$container.*\"}\r\n| facets 3\r\n| sort by(hits) desc"
      }
     ]
    },
    {
     "title": "Top 10 log patterns (collapse_nums)",
     "type": "table",
     "description": "Shows most common log patterns on the time range\n\nhttps://docs.victoriametrics.com/victorialogs/logsql/#collapse_nums-pipe",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 160 },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\", container_name=~\"$container.*\"}\r\n| collapse_nums prettify\r\n| top 10 by(_msg)"
      }
     ]
    },
    {
     "title": "Logs - Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "logs/s" } },
     "targets": [
      {
       "expr": "_stream:{host=\"$host\", source_type=\"$source_type\", container_name=~\"$container.*\"}\r\n| stats by (container_name) rate() logs_rate\r\n| filter logs_rate: > 0",
       "legendFormat": "logs"
      }
     ]
    }
   ]
  },
  { "title": "Logs - Raw", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Logs",
   "type": "logs",
   "description": "A list of log messages.\nHere, the text is output only from [log.msg].\nThe text is highlighted according to its level from [log.level].\n\nFor the logs to be displayed correctly, the application must:\n- Write the log in json format \n- Write text in [log.msg]\n- Record the level in [log.level]\n\nIf the application writes logs in plain text, then before it is compiled, the collector parses the text for keywords to get [log.level]. Most often, such logs have a level of [unknown]",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "desc",
     "expr": "_stream:{host=\"$host\", source_type=\"$source_type\", container_name=~\"$container.*\"}\r\n| log.level:\"$level\"\r\n| $filter\r\n| sort by (_time)\r\n| limit $limit "
    }
   ]
  },
  {
   "title": "Logs - History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "_stream:{host=\"$host\", source_type=\"$source_type\", container_name=~\"$container.*\"}\r\n| log.level:\"$level\"\r\n| $filter\r\n| stats by (log.level) count() levels\r\n| sort by (levels desc)\r\n| limit 10",
     "legendFormat": "{{ log.level }}"
    }
   ]
  }
 ]
}